version: 2.1

orbs:
  docker: circleci/docker@2.1.4

workflows:
  publish-image:
    jobs:
      - docker/publish:
          after_build:
              - run:
                  name: Build Report
                  command: echo 'build was successful..'
          before_build:
              - run:
                  name: Begin Build
                  command: echo 'build process about to start'
          image: $DOCKER_USERNAME/red-rain
          docker-username: DOCKER_USERNAME
          docker-password: DOCKER_PASSWORD
          tag: latest