version: 2.1

orbs:
  docker: circleci/docker@2.1.4

workflows:
  publish-image:
    jobs:
      - docker/publish:
          after_build:
            - run:
              name: Build Report
              command: echo 'build was successful..'
          before_build:
            - run:
              name: Begin Build
              command: echo 'build process about to start'
          image: $D_USER/red-rain
          docker-username: D_USER
          docker-password: D_PASS
          tag: latest